### ISSUE TITLE
No handling of duplicate URLs.

### ISSUE THREAD

**Issue by ralphembree** [nick-2017/jsorgshortener#1]
I just tested your website, and I used https://dns.js.org as the target. I was given a short URL that I tested and confirmed was working. Curious, I tried again and got another short URL. To conserve on characters, it's better to save the shortened URL to be used for future requests of the same long URL.

**Comment by nick-2017** [comment]
Fixed that in [this comment](https://github.com/nick-2017/jsorgshortener/commit/7f6acbc138b57e3d04074affe3d90fbea2f68a72)
